### ISSUE TITLE
feat: support osc escape sequences for status

### ISSUE THREAD

**Issue by castrojo** [ublue-os/uupd#25]
FYI, and we're shipping ptyxis already, might as well look nice!

https://blogs.gnome.org/chergert/2024/12/03/ptyxis-progress-support/

**Comment by tulilirockz** [comment]
Not even Ptyxis nightly has it yet, we gotta wait until the GNOME Gitlab's CI works so that we can get the newest build. Some references to implementing this:

- https://gitlab.gnome.org/GNOME/vte/-/issues/2845
- https://learn.microsoft.com/en-us/windows/terminal/tutorials/progress-bar-sequences
- https://conemu.github.io/en/AnsiEscapeCodes.html#ConEmu_specific_OSC
